#lang racket
(require 2htdp/image)
(require 2htdp/universe)

(define flag (rectangle 100 61.8 "solid" "red"))
(define big-star (star 15 "solid" "yellow"))
(overlay big-star flag)
(triangle 40 "solid" "tan")
(rhombus 40 60 "outline" "magenta")
(circle 20 "solid" "green")
(regular-polygon 50 3 "outline" "red")
(regular-polygon 40 4 "solid" "blue")
(regular-polygon 20 8 "solid" "red")
(ellipse 50 30 "solid" "purple")
(overlay (ellipse 10 10 "solid" "red")
           (ellipse 20 20 "solid" "black")
           (ellipse 30 30 "solid" "red")
           (ellipse 40 40 "solid" "black")
           (ellipse 50 50 "solid" "red")
           (ellipse 60 60 "solid" "black"))
(overlay/xy (rectangle 20 20 "solid" "red")
              10 10
              (rectangle 20 20 "solid" "black"))
(radial-star 8 8 64 "solid" "darkslategray")
;(define (my-star x)
;   (radial-star x 8 64 "solid" "darkslategray"))
(define (my-star x)
          (radial-star (+ (remainder x 100) 2) 8 64 "solid" "darkslategray"))
(place-image (my-star 30) 75 75 (empty-scene 150 150))
(animate (lambda (x)
           (place-image (my-star (+ x 2)) 75 75 (empty-scene 150 150))))

