(define (find m)
  (define (fmax ls)
    (define (iter max ls)
      (if (null? ls)
          max
          (if (> (car ls) max)
              (iter (car ls) (cdr ls))
              (iter max (cdr ls)))))
    (iter (car ls) ls))
  (define (fmin ls)
    (define (iter min ls)
      (if (null? ls)
          min
          (if (< (car ls) min)
              (iter (car ls) (cdr ls))
              (iter min (cdr ls)))))
    (iter (car ls) ls))
(define (dispatch m)
  (cond ((eq? m 'fmax) fmax)
        ((eq? m 'fmin) fmin)
        (else (error "错误指令！"))))
  (dispatch m))