#lang racket

;模拟面向对象
(define (point name method x y)
  (define (CartesianPt method)
    (cond ((eq? method 'distanceTo)
           (distanceTo 'CartesianPt))
          (else error)))
  (define (ManhattanPt method)
    (cond ((eq? method 'distanceTo)
           (distanceTo 'ManhattanPt))
          (else error)))
  (define (distanceTo name)
    (cond ((eq? name 'CartesianPt)
           (sqrt (+ (* x x)(* y y))))
          ((eq? name 'ManhattanPt)
           (+ x y))
          (else error)))
  (define (Select name)
    (cond ((eq? name 'CartesianPt)
           (CartesianPt method))
          ((eq? name 'ManhattanPt)
           (ManhattanPt method))
          (else error)))
  (Select name))